---
device_file: "templates/snmp_device_list.yml"

zabbix_url: "{{ lookup('env', 'ZABBIX_API_URL') }}"
zabbix_user: "{{ lookup('env', 'ZABBIX_USERNAME') }}"
zabbix_password: "{{ lookup('env', 'ZABBIX_PASSWORD') }}"
